/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;

import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 *
 * @author Tojoniriako
 */
public class Accueil extends javax.swing.JFrame {
    private ResultSet rs;
    private Object st;
    private Object dtm;

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
        setExtendedState(Accueil.MAXIMIZED_BOTH);
        Table();
        Table2();
        Table3();
        Idcustomer();
        Idroom();
        
        client_id.setBackground(new java.awt.Color(0,0,0,1));
        client_name.setBackground(new java.awt.Color(0,0,0,1));
        client_phone.setBackground(new java.awt.Color(0,0,0,1));
       
        client_address.setBackground(new java.awt.Color(0,0,0,1));
        client_city.setBackground(new java.awt.Color(0,0,0,1));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        CUSTOMER = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        client_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        client_phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        client_address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        client_city = new javax.swing.JComboBox();
        button1 = new java.awt.Button();
        Edit = new java.awt.Button();
        delete = new java.awt.Button();
        client_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        buttonImprimCust = new java.awt.Button();
        ROOM = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        room_id = new javax.swing.JTextField();
        room_type = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        room_prices = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        jLabel32 = new javax.swing.JLabel();
        room_about = new javax.swing.JTextField();
        addRoom = new java.awt.Button();
        editRoom = new java.awt.Button();
        deleteRoom = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRoom = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        print_room = new java.awt.Button();
        RESERVATION = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        customer_name = new javax.swing.JTextField();
        id_customerCombo = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        customer_phone = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        heure_entry = new javax.swing.JTextField();
        heure_out = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        id_roomCombo = new javax.swing.JComboBox();
        prices_room = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        type_room = new javax.swing.JTextField();
        dateRes = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableReservation = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        button6 = new java.awt.Button();
        delete_res = new java.awt.Button();
        edit_res = new java.awt.Button();
        add_res = new java.awt.Button();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setForeground(new java.awt.Color(0, 204, 204));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CUSTOMER.setForeground(new java.awt.Color(0, 204, 204));
        CUSTOMER.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setForeground(new java.awt.Color(199, 226, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUSTOMER");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(199, 226, 255));
        jLabel3.setText("id_Customer");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 90, -1));

        client_name.setFont(client_name.getFont().deriveFont(client_name.getFont().getSize()+2f));
        client_name.setForeground(new java.awt.Color(255, 255, 255));
        client_name.setBorder(null);
        jPanel5.add(client_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 135, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(199, 226, 255));
        jLabel4.setText("No. Phone");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("______________________");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, 30));

        client_phone.setFont(client_phone.getFont().deriveFont(client_phone.getFont().getSize()+2f));
        client_phone.setForeground(new java.awt.Color(255, 255, 255));
        client_phone.setBorder(null);
        jPanel5.add(client_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 135, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(199, 226, 255));
        jLabel5.setText("Address");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("______________________");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, 30));

        client_address.setFont(client_address.getFont().deriveFont(client_address.getFont().getSize()+2f));
        client_address.setForeground(new java.awt.Color(255, 255, 255));
        client_address.setBorder(null);
        jPanel5.add(client_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 135, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(199, 226, 255));
        jLabel6.setText("City");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        client_city.setFont(client_city.getFont().deriveFont(client_city.getFont().getSize()+2f));
        client_city.setForeground(new java.awt.Color(255, 255, 255));
        client_city.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Antananarivo", "Mahajanga", "Toamasina", "Fianarantsoa", "Toliara", "Antsirabe", "Diego", "Morondava", "Saint Marie", "NosyBe Hell Ville", " " }));
        client_city.setBorder(null);
        client_city.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(client_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 135, -1));

        button1.setBackground(new java.awt.Color(0, 204, 204));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Add");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel5.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 328, 93, 42));

        Edit.setBackground(new java.awt.Color(0, 255, 102));
        Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Edit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Edit.setForeground(new java.awt.Color(255, 255, 255));
        Edit.setLabel("Edit");
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMouseClicked(evt);
            }
        });
        jPanel5.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 328, 93, 42));

        delete.setBackground(new java.awt.Color(255, 0, 0));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setLabel("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel5.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 328, 93, 42));

        client_id.setEditable(false);
        client_id.setFont(client_id.getFont().deriveFont(client_id.getFont().getSize()+3f));
        client_id.setForeground(new java.awt.Color(255, 255, 255));
        client_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        client_id.setBorder(null);
        client_id.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        client_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_idActionPerformed(evt);
            }
        });
        jPanel5.add(client_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 135, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("X");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 30, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("______________________");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 164, 160, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(199, 226, 255));
        jLabel12.setText("Name");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        CUSTOMER.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 0, 460, 740));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 204, 204));
        jTable1.setRowHeight(22);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        CUSTOMER.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 84, 850, 340));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Guest list");
        CUSTOMER.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 850, -1));

        buttonImprimCust.setBackground(new java.awt.Color(153, 153, 153));
        buttonImprimCust.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonImprimCust.setForeground(new java.awt.Color(255, 255, 255));
        buttonImprimCust.setLabel("Print");
        buttonImprimCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImprimCustActionPerformed(evt);
            }
        });
        CUSTOMER.add(buttonImprimCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 430, 131, 45));

        jTabbedPane1.addTab("CUSTOMER", CUSTOMER);

        ROOM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ROOM");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(199, 226, 255));
        jLabel14.setText("id_Room");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(199, 226, 255));
        jLabel15.setText("Room type");

        room_id.setEditable(false);
        room_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        room_id.setText(" ");

        room_type.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        room_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Classic", "Premium", "VIP" }));
        room_type.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(199, 226, 255));
        jLabel16.setText("Prices");

        room_prices.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 0, 0));
        label1.setName(""); // NOI18N
        label1.setText("X");
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(199, 226, 255));
        jLabel32.setText("About");

        addRoom.setBackground(new java.awt.Color(0, 204, 204));
        addRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addRoom.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addRoom.setForeground(new java.awt.Color(255, 255, 255));
        addRoom.setLabel("Add");
        addRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addRoomMouseClicked(evt);
            }
        });
        addRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomActionPerformed(evt);
            }
        });

        editRoom.setBackground(new java.awt.Color(0, 255, 102));
        editRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editRoom.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        editRoom.setForeground(new java.awt.Color(255, 255, 255));
        editRoom.setLabel("Edit");
        editRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editRoomMouseClicked(evt);
            }
        });

        deleteRoom.setBackground(new java.awt.Color(255, 0, 0));
        deleteRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteRoom.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        deleteRoom.setForeground(new java.awt.Color(255, 255, 255));
        deleteRoom.setLabel("Delete");
        deleteRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteRoomMouseClicked(evt);
            }
        });
        deleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16))
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(room_id)
                    .addComponent(room_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(room_prices, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(room_about))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(editRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(deleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(room_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(room_prices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(room_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(room_about, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(380, Short.MAX_VALUE))
        );

        ROOM.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 400, 750));

        jTableRoom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableRoomMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableRoom);

        ROOM.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 840, 310));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("List of rooms");
        ROOM.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 850, 30));

        print_room.setBackground(new java.awt.Color(0, 204, 204));
        print_room.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        print_room.setForeground(new java.awt.Color(255, 255, 255));
        print_room.setLabel("Print");
        print_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_roomActionPerformed(evt);
            }
        });
        ROOM.add(print_room, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 420, 120, 50));

        jTabbedPane1.addTab("ROOM", ROOM);

        RESERVATION.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 204));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("RESERVATION");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 270, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("id_Customer");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Name");

        customer_name.setEditable(false);
        customer_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        id_customerCombo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        id_customerCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Id_customer" }));
        id_customerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_customerComboActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("No. Phone");

        customer_phone.setEditable(false);
        customer_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Reservation Date");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Entry Time");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Out Time");

        heure_entry.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        heure_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heure_entryActionPerformed(evt);
            }
        });

        heure_out.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("id_Room");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Prices");

        id_roomCombo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        id_roomCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Id_room" }));
        id_roomCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_roomComboActionPerformed(evt);
            }
        });

        prices_room.setEditable(false);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Room Type");

        type_room.setEditable(false);
        type_room.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customer_name, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(customer_phone)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(id_customerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(279, 279, 279)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(type_room))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prices_room, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_roomCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(heure_entry)
                        .addComponent(heure_out, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateRes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel20))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(heure_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22)
                                .addComponent(customer_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(heure_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(id_roomCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_customerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel27)
                            .addComponent(prices_room))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type_room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1270, 200));

        jTableReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableReservationMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTableReservation);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 1230, 150));

        button6.setBackground(new java.awt.Color(153, 153, 153));
        button6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button6.setForeground(new java.awt.Color(255, 255, 255));
        button6.setLabel("Print");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        delete_res.setBackground(new java.awt.Color(255, 0, 0));
        delete_res.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        delete_res.setForeground(new java.awt.Color(255, 255, 255));
        delete_res.setLabel("Delete");
        delete_res.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_resMouseClicked(evt);
            }
        });

        edit_res.setBackground(new java.awt.Color(0, 255, 102));
        edit_res.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        edit_res.setForeground(new java.awt.Color(255, 255, 255));
        edit_res.setLabel("Edit");
        edit_res.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_resMouseClicked(evt);
            }
        });

        add_res.setBackground(new java.awt.Color(0, 204, 204));
        add_res.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        add_res.setForeground(new java.awt.Color(255, 255, 255));
        add_res.setLabel("Add");
        add_res.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_resMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addComponent(add_res, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(edit_res, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(delete_res, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(add_res, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(edit_res, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_res, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 930, 90));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("X");
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 20, 30));

        RESERVATION.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 480));

        jTabbedPane1.addTab("RESERVATION", RESERVATION);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1380, 770));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1410, 780));

        setSize(new java.awt.Dimension(1433, 797));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        try {
            if (client_name.getText().isEmpty()||client_phone.getText().isEmpty()||client_address.getText().isEmpty()||client_city.getSelectedItem().toString().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please entrer your customer");
            }else{
                        Config cn = new Config();
                        Statement st = cn.cn.createStatement();
                        String sql = "INSERT INTO tb_customer (name,phone,address,city) VALUES ('"+client_name.getText()+"','"+client_phone.getText()+"','"+client_address.getText()+"','"+client_city.getSelectedItem().toString()+"')";
                        st.executeUpdate(sql);
                        st.close();
                        JOptionPane.showMessageDialog(this, "Customer Add");
                        Table();
                        client_name.setText("");
                        client_phone.setText("");
                        client_address.setText("");
                        client_city.setSelectedItem("");
                        
            }
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_button1MouseClicked

    public void Table(){
        String [] tb_customer={"Id_customer","Name","Phone","Address","City"};
        String [] afficher= new String[6];
        DefaultTableModel model = new DefaultTableModel(null, tb_customer);
        try {
            Config cn = new Config();
            Statement st = cn.cn.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_customer");
            
                while (rs.next()) {                
                     afficher[0] = rs.getString("id_customer");
                     afficher[1] = rs.getString("name");
                     afficher[2] = rs.getString("phone");
                     afficher[3] = rs.getString("address");
                     afficher[4] = rs.getString("city");
                     model.addRow(afficher);
            }
                jTable1.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseClicked
        // TODO add your handling code here:
        try {
            if (client_name.getText().isEmpty()||client_phone.getText().isEmpty()||client_address.getText().isEmpty()||client_address.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please entrer your customer");
            }else{
                    Config cn = new Config();
                    Statement st = cn.cn.createStatement();
                    String sql = "update tb_customer set name='"+client_name.getText()+"' , phone='"+client_phone.getText()+"', address='"+client_address.getText()+"', city='"+client_city.getSelectedItem().toString()+"' where id_customer="+client_id.getText()+"";
                    st.executeUpdate(sql);
                    st.close();
                    JOptionPane.showMessageDialog(this, "Customer Edit");
                    Table();
                    client_id.setText("");
                    client_name.setText("");
                    client_phone.setText("");
                    client_address.setText("");
                    client_city.setSelectedItem("");
                        
            }
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_EditMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         try {
            if (client_name.getText().isEmpty()||client_phone.getText().isEmpty()||client_address.getText().isEmpty()||client_address.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please entrer your customer");
            }else{
                    Config cn = new Config();
                    Statement st = cn.cn.createStatement();
                    String sql = "delete from tb_customer where id_customer="+client_id.getText()+"";
                    st.executeUpdate(sql);
                    st.close();
                    JOptionPane.showMessageDialog(this, "Customer deleted");
                    Table();
                    client_id.setText("");
                    client_name.setText("");
                    client_phone.setText("");
                    client_address.setText("");
                    client_city.setSelectedItem("");
                        
            }
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Login nc = new Login();
        nc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        int i = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        client_id.setText(model.getValueAt(i, 0).toString());
        client_name.setText(model.getValueAt(i, 1).toString());
        client_phone.setText(model.getValueAt(i, 2).toString());
        client_address.setText(model.getValueAt(i, 3).toString());
        client_city.setSelectedItem(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_jTable1MouseReleased

    private void client_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client_idActionPerformed

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        // TODO add your handling code here:
        Login nc = new Login();
        nc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_label1MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        Login nc = new Login();
        nc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void addRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRoomMouseClicked
        // TODO add your handling code here:
        try {
            if (room_prices.getText().isEmpty()||room_type.getSelectedItem().toString().isEmpty()||room_about.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter your room");
            } else {
                Config cn = new Config();
                Statement st = cn.cn.createStatement();
                String sql;
                sql = "INSERT INTO `tb_room` (`prices`, `room_type`, `room_about`)  VALUES ('"+room_prices.getText()+"','"+room_type.getSelectedItem().toString()+"','"+room_about.getText()+"')";
                st.executeUpdate(sql);
                st.close();
                JOptionPane.showMessageDialog(this, "Room Add");
                Table();
                room_prices.setText(" ");
                room_type.setSelectedItem("");
                room_about.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }  
    }//GEN-LAST:event_addRoomMouseClicked
    public void Table2(){
        String [] tb_room={"Id_room","Prices","Room_type","Room_about"};
        String [] afficher= new String[5];
        DefaultTableModel model = new DefaultTableModel(null, tb_room);
        try {
            Config cn = new Config();
            Statement st = cn.cn.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_room");
            
                while (rs.next()) {                
                     afficher[0] = rs.getString("id_room");
                     afficher[1] = rs.getString("prices");
                     afficher[2] = rs.getString("room_type");
                     afficher[3] = rs.getString("room_about");
                     model.addRow(afficher);
            }
                jTableRoom.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
  
    private void addRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRoomActionPerformed

    private void editRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editRoomMouseClicked
        // TODO add your handling code here:
        try {
            if (room_prices.getText().isEmpty()||room_type.getSelectedItem().toString().isEmpty()||room_about.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter your room");
            }else{
                    Config cn = new Config();
                    Statement st = cn.cn.createStatement();
                    String sql = "update tb_room set prices='"+room_prices.getText()+"' , room_type='"+room_type.getSelectedItem().toString()+"', room_about='"+room_about.getText()+"' where id_room="+room_id.getText()+"";
                    st.executeUpdate(sql);
                    st.close();
                    JOptionPane.showMessageDialog(this, "Customer Edit");
                    Table2();
                    room_id.setText("");
                    room_prices.setText(" ");
                    room_type.setSelectedItem("");
                    room_about.setText("");
                        
            }
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_editRoomMouseClicked

    private void deleteRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteRoomMouseClicked
        // TODO add your handling code here:
         try {
            if (room_prices.getText().isEmpty()||room_type.getSelectedItem().toString().isEmpty()||room_about.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter your room");
            }else{
                    Config cn = new Config();
                    Statement st = cn.cn.createStatement();
                    String sql = "delete from tb_room where id_room="+room_id.getText()+"";
                    st.executeUpdate(sql);
                    st.close();
                    JOptionPane.showMessageDialog(this, "Customer deleted");
                    Table2();
                    room_id.setText("");
                    room_prices.setText(" ");
                    room_type.setSelectedItem("");
                    room_about.setText("");
                        
            }
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_deleteRoomMouseClicked

    private void deleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteRoomActionPerformed

    private void jTableRoomMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRoomMouseReleased
        // TODO add your handling code here:
        int i = jTableRoom.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTableRoom.getModel();
        room_id.setText(model.getValueAt(i, 0).toString());
        room_prices.setText(model.getValueAt(i, 1).toString());
        room_type.setSelectedItem(model.getValueAt(i, 2).toString());
        room_about.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_jTableRoomMouseReleased

    private void buttonImprimCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImprimCustActionPerformed
        // TODO add your handling code here:
        String titre = "Guest list";
        Divers.imprimerJtable(jTable1, titre);
    }//GEN-LAST:event_buttonImprimCustActionPerformed

    private void print_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_roomActionPerformed
        // TODO add your handling code here:
        String titre = "List of room";
        Divers.imprimerJtable(jTableRoom, titre);
    }//GEN-LAST:event_print_roomActionPerformed

    @SuppressWarnings("empty-statement")
    private void add_resMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_resMouseClicked
        try {
            if (customer_phone.getText().isEmpty()|| id_roomCombo.getSelectedItem().toString().isEmpty()|| prices_room.getText().isEmpty()|| type_room.getText().isEmpty()|| heure_entry.getText().isEmpty()|| id_customerCombo.getSelectedItem().toString().isEmpty()||  customer_name.getText().isEmpty()|| heure_out.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter your reservation");
            } else {
                Config cn = new Config();
                Statement st = cn.cn.createStatement();
                String sql;
                sql = "INSERT INTO `tb_reservation`(`id_customer`, `id_room`, `heure_out`, `dateRes`, `time_entry`) VALUES ('"+id_customerCombo.getSelectedItem().toString()+"','"+id_roomCombo.getSelectedItem().toString()+"','"+heure_out.getText()+"','"+dateRes.getText()+"','"+heure_entry.getText()+"')";
                int executeUpdate = st.executeUpdate(sql);
                st.close();
                JOptionPane.showMessageDialog(this, "Reservation Add");
                Table3();
                id_customerCombo.setSelectedItem(" ");
                customer_name.setText("");
                customer_phone.setText("");
                id_roomCombo.setSelectedItem(" ");
                prices_room.setText("");
                type_room.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_add_resMouseClicked

    private void jTableReservationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReservationMouseReleased
        // TODO add your handling code here:
        int i = jTableReservation.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTableReservation.getModel();
        id_customerCombo.setSelectedItem(model.getValueAt(i, 0).toString());
        id_roomCombo.setSelectedItem(model.getValueAt(i, 1).toString());
        dateRes.setText(model.getValueAt(i, 3).toString());
        heure_out.setText(model.getValueAt(i, 4).toString());
        heure_entry.setText(model.getValueAt(i, 2).toString());
    }//GEN-LAST:event_jTableReservationMouseReleased

    private void edit_resMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_resMouseClicked
        // TODO add your handling code here:
        try {
            if (id_customerCombo.getSelectedItem().toString().isEmpty()|| customer_name.getText().isEmpty()|| customer_phone.getText().isEmpty()|| id_roomCombo.getSelectedItem().toString().isEmpty()|| prices_room.getText().isEmpty()|| type_room.getText().isEmpty()|| heure_entry.getText().isEmpty()|| heure_out.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter your reservation");
            } else {
                Config cn = new Config();
                Statement st = cn.cn.createStatement();
                String sql;
                sql = "update tb_room set id_customer ='"+id_customerCombo.getSelectedItem().toString()+"',id_room='"+id_roomCombo.getSelectedItem().toString()+"',heure_out='"+heure_out.getText()+"',dateRes='"+dateRes.getText()+"',time_entry='"+heure_entry.getText()+"')";
                st.executeUpdate(sql);
                st.close();
                JOptionPane.showMessageDialog(this, "Reservation Edit");
                Table3();
                id_customerCombo.setSelectedItem(" ");
                customer_name.setText("");
                customer_phone.setText("");
                id_roomCombo.setSelectedItem(" ");
                prices_room.setText("");
                type_room.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_edit_resMouseClicked

    private void delete_resMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_resMouseClicked
        // TODO add your handling code here:
        try {
            if (id_customerCombo.getSelectedItem().toString().isEmpty()|| customer_name.getText().isEmpty()|| customer_phone.getText().isEmpty()|| id_roomCombo.getSelectedItem().toString().isEmpty()|| prices_room.getText().isEmpty()|| type_room.getText().isEmpty()|| heure_entry.getText().isEmpty()|| heure_out.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter your reservation");
            }else{
                    Config cn = new Config();
                    Statement st = cn.cn.createStatement();
                    String sql = "delete from tb_reservation where id_customer="+id_customerCombo.getSelectedItem().toString()+"";
                    st.executeUpdate(sql);
                    st.close();
                    JOptionPane.showMessageDialog(this, "Reservation deleted");
                    Table3();
                    id_customerCombo.setSelectedItem(" ");
                    customer_name.setText("");
                    customer_phone.setText("");
                    id_roomCombo.setSelectedItem(" ");
                    prices_room.setText("");
                    type_room.setText("");
                        
            }
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_delete_resMouseClicked

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        String titre = "Reservation List";
        Divers.imprimerJtable(jTableReservation, titre);
    }//GEN-LAST:event_button6ActionPerformed
    
    private void id_customerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_customerComboActionPerformed
        // TODO add your handling code here:
        String idCustomer = (String) id_customerCombo.getSelectedItem();
        try {
            Config cn = new Config();
            Statement st = cn.cn.createStatement();
            rs = st.executeQuery("SELECT `name`, `phone` FROM tb_customer WHERE id_customer='"+idCustomer+"'");
            
            if (rs.next())
            {
                customer_name.setText(rs.getString(1));
                customer_phone.setText(rs.getString(2));
            }
        } catch (Exception ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_id_customerComboActionPerformed
    public void Idroom(){
        try {
            Config cn = new Config();
            Statement st = cn.cn.createStatement();
            rs = st.executeQuery("SELECT id_room FROM tb_room");
            
            while (rs.next())
            {
                id_roomCombo.addItem(rs.getString(1));
            }
        } catch (Exception ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    private void id_roomComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_roomComboActionPerformed
        // TODO add your handling code here:
         String idRoom = (String) id_roomCombo.getSelectedItem();
        try {
            Config cn = new Config();
            Statement st = cn.cn.createStatement();
            rs = st.executeQuery("SELECT `prices`, `room_type` FROM tb_room WHERE id_room='"+idRoom+"'");
            
            if (rs.next())
            {
                prices_room.setText(rs.getString(1));
                type_room.setText(rs.getString(2));
            }
        } catch (Exception ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_id_roomComboActionPerformed

    private void heure_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heure_entryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heure_entryActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         LocalDate today = LocalDate.now();
         dateRes.setText(today.toString());
         
         LocalTime now = LocalTime.now();
         heure_entry.setText(now.toString());
         heure_out.setText(now.toString());
        
    }//GEN-LAST:event_formWindowActivated
    public void Idcustomer(){
        try {
            Config cn = new Config();
            Statement st = cn.cn.createStatement();
            rs = st.executeQuery("SELECT id_customer FROM tb_customer");
            
            while (rs.next())
            {
                id_customerCombo.addItem(rs.getString(1));
            }
        } catch (Exception ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    public void Table3(){
        String [] tb_reservation={"Id_customer","Id_room","Time_entry","Date Res","Heure_out"};
        String [] afficher= new String[6];
        DefaultTableModel model = new DefaultTableModel(null, tb_reservation);
        try {
            Config cn = new Config();
            Statement st = cn.cn.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_reservation");
            
                while (rs.next()) {                
                     afficher[0] = rs.getString("id_customer");
                     afficher[1] = rs.getString("id_room");
                     afficher[2] = rs.getString("heure_out");
                     afficher[3] = rs.getString("dateRes");
                     afficher[4] = rs.getString("time_entry");
                     model.addRow(afficher);
            }
                jTableReservation.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CUSTOMER;
    private java.awt.Button Edit;
    private javax.swing.JPanel RESERVATION;
    private javax.swing.JPanel ROOM;
    private java.awt.Button addRoom;
    private java.awt.Button add_res;
    private java.awt.Button button1;
    private java.awt.Button button6;
    private java.awt.Button buttonImprimCust;
    private javax.swing.JTextField client_address;
    private javax.swing.JComboBox client_city;
    private javax.swing.JTextField client_id;
    private javax.swing.JTextField client_name;
    private javax.swing.JTextField client_phone;
    private javax.swing.JTextField customer_name;
    private javax.swing.JTextField customer_phone;
    private javax.swing.JTextField dateRes;
    private java.awt.Button delete;
    private java.awt.Button deleteRoom;
    private java.awt.Button delete_res;
    private java.awt.Button editRoom;
    private java.awt.Button edit_res;
    private javax.swing.JTextField heure_entry;
    private javax.swing.JTextField heure_out;
    private javax.swing.JComboBox id_customerCombo;
    private javax.swing.JComboBox id_roomCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableReservation;
    private javax.swing.JTable jTableRoom;
    private java.awt.Label label1;
    private javax.swing.JTextField prices_room;
    private java.awt.Button print_room;
    private javax.swing.JTextField room_about;
    private javax.swing.JTextField room_id;
    private javax.swing.JTextField room_prices;
    private javax.swing.JComboBox room_type;
    private javax.swing.JTextField type_room;
    // End of variables declaration//GEN-END:variables

    private static class cn {

        public cn() {
        }
    }
}
